package com.example.sqsreadandwritedybamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.apache.commons.lang3.StringUtils;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "car")
public class Car {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String carId;


    @DynamoDBIndexHashKey(globalSecondaryIndexName = "modelMaxSpeedIndex")
    @DynamoDBAttribute(attributeName = "modelMaxSpeed")
    private String modelMaxSpeed;

    @DynamoDBAttribute
    private String model;

    @DynamoDBAttribute
    private String color;

    @DynamoDBAttribute
    private Integer maxSpeed;
}
